// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPkYXa5MnHuhMNw9WqPNqFJb9zGZuXXI',
    appId: '1:814273167111:web:5da669a298002f82844fa2',
    messagingSenderId: '814273167111',
    projectId: 'diplo-3c670',
    authDomain: 'diplo-3c670.firebaseapp.com',
    storageBucket: 'diplo-3c670.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqBV1K-jrNXpGecounVfrk67mCP-D10Lw',
    appId: '1:814273167111:android:9919787b21cdebf4844fa2',
    messagingSenderId: '814273167111',
    projectId: 'diplo-3c670',
    storageBucket: 'diplo-3c670.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBPkYXa5MnHuhMNw9WqPNqFJb9zGZuXXI',
    appId: '1:814273167111:web:5da669a298002f82844fa2',
    messagingSenderId: '814273167111',
    projectId: 'diplo-3c670',
    authDomain: 'diplo-3c670.firebaseapp.com',
    storageBucket: 'diplo-3c670.firebasestorage.app',
  );

}